# Generated by Django 4.0.3 on 2022-04-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='NAME')),
                ('host', models.CharField(max_length=30, verbose_name='HOST')),
                ('port', models.CharField(max_length=30, verbose_name='PORT')),
                ('login', models.CharField(max_length=30, verbose_name='LOGIN')),
                ('password', models.CharField(max_length=30, verbose_name='PASSWORD')),
            ],
        ),
    ]
